services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    env_file:
      - .env.${NODE_ENV}
    stdin_open: true
    tty: true
    command: npm run dev

  storybook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6006:6006"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
    command: npm run storybook -- --host 0.0.0.0 --no-open