services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    env_file:
      - .env.${NODE_ENV}
    stdin_open: true
    tty: true